# Generated by Django 5.2.4 on 2025-07-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_menuitem_category_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Flat delivery fee in GBP (ignored if free delivery is enabled)', max_digits=5),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_zones',
            field=models.TextField(blank=True, help_text='Comma-separated UK postcodes where delivery is available (e.g., SW1A, SW1E)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='free_delivery',
            field=models.BooleanField(default=False, help_text='Offer free delivery regardless of fee?'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='offers_delivery',
            field=models.BooleanField(default=False, help_text='Does this restaurant offer delivery?'),
        ),
    ]
