# Generated by Django 5.2.4 on 2025-07-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_delivery_fee_restaurant_delivery_zones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='delivery_zones',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='max_delivery_time_minutes',
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='free_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='offers_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
