# Generated by Django 5.2.4 on 2025-08-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_remove_restaurant_delivery_zones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghour',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='openinghour',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openinghour',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
