# Generated by Django 5.2.4 on 2025-08-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_openinghour_is_closed_alter_openinghour_close_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='images/default-restaurant.png', help_text='Main restaurant image (16:9 PNG or JPG)', upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='RestaurantImage',
        ),
    ]
