# Generated by Django 5.2.4 on 2025-08-04 22:44

import restaurants.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_image_delete_restaurantimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='address',
            new_name='street_name',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='free_delivery',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='max_delivery_time_minutes',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='offers_delivery',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='postal_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='street_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, help_text='Main restaurant image (16:9 PNG or JPG)', null=True, upload_to='restaurants/', validators=[restaurants.validators.validate_1920x1080_image]),
        ),
    ]
