# Generated by Django 5.2.4 on 2025-08-04 22:46

import django.db.models.deletion
import menu.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0007_rename_address_restaurant_street_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('restaurant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Upload a square image (1:1) at least 600x600 px', null=True, upload_to='menu_items/', validators=[menu.validators.validate_square_image])),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('allergens', models.CharField(blank=True, help_text='Comma-separated allergens (e.g., nuts, gluten, dairy)', max_length=255)),
                ('calories', models.PositiveIntegerField(help_text='Calories per portion')),
                ('protein', models.PositiveIntegerField(help_text='Protein (g)')),
                ('carbs', models.PositiveIntegerField(help_text='Carbs (g)')),
                ('fat', models.PositiveIntegerField(help_text='Fat (g)')),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.menucategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
