# Generated by Django 5.2.4 on 2025-07-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='allergens',
            field=models.CharField(blank=True, help_text='Comma-separated list of allergens (e.g., nuts, gluten, dairy)', max_length=255),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='Calories per portion', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='carbs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Carbs (g)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fat (g)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Protein (g)', max_digits=5, null=True),
        ),
    ]
